USE video_games_quiz_db;

CREATE TABLE genres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO genres (name) VALUES
('Action-Adventure'),
('Action RPG'),
('Sandbox'),
('Platformer'),
('FPS'),
('Battle Royale'),
('Survival Horror'),
('Roguelike'),
('Simulation'),
('Social Simulation'),
('Racing'),
('Fighting'),
('TPS'),
('JRPG'),
('MOBA'),
('VR FPS'),
('Puzzle-Platformer'),
('Survival'),
('Metroidvania'),
('RPG'),
('Run and Gun'),
('Roguelite'),
('Deckbuilder'),
('Social Deduction'),
('Platform Battle Royale'),
('Sports'),
('Hack and Slash'),
('Action'),
('Stealth'),
('Immersive Sim'),
('Turn-based RPG'),
('Adventure'),
('Life Simulation'),
('City-building'),
('Strategy'),
('Grand Strategy'),
('Construction and Management Simulation'),
('MMORPG'),
('Puzzle'),
('Top-down Shooter'),
('Action-Platformer'),
('FPS/TPS'),
('Fishing');
